name: Formatar Código com Eslint

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Node.js e pnpm
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install -g pnpm

      - name: Instalar dependências do projeto
        run: pnpm install

      - name: Verificar alterações não commitadas
        run: |
          if git diff --exit-code; then
            echo "No changes to formatting. Leaving..."
            exit 0
          fi

      - name: Formatar código
        run: pnpm format

      - name: Commit das alterações formatadas
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Automating code formatting with Github Actions"
          git push
