name: Formatar Código com Eslint

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Node.js e pnpm
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install -g pnpm

      - name: Instalar dependências do projeto
        run: pnpm install
        
      - name: Verificar alterações no código
        id: check_changes
        run: echo ::set-output name=has_changes::$(git status --porcelain)

      - name: Formatar código
        run: pnpm format
        if: steps.check_changes.outputs.has_changes == 'M'  # Executa somente se houver alterações

      - name: Commit das alterações formatadas (se houver)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git add .
            git commit -m "Automating code formatting with Github Actions"
            git push
          else
            echo "Nenhuma alteração para formatar. Saindo..."
          fi
